create schema bft;

GRANT USAGE ON SCHEMA bft TO GROUP bft;

ALTER TABLE bft.BELIEF ADD CONSTRAINT PK_BELIEF PRIMARY KEY(BELIEF_ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON bft.BELIEF TO GROUP bft;  