CREATE SCHEMA bft;

CREATE TABLE bft.BELIEF(
	BELIEF_ID INTEGER NOT NULL IDENTITY,
	BELIEF_TYPE VARCHAR(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	STARTING_PERIOD DATE,
	ENDING_PERIOD DATE,
	COMMENT_TEXT VARCHAR(1000),
	WORSHIP_TYPE VARCHAR(20),
	DIVINE_LAW_NAME VARCHAR(100),
	DIVINITY_EQUALITY_TYPE VARCHAR(10)
);

CREATE TABLE bft.REFERENCE(
	REFERENCE_ID INTEGER NOT NULL IDENTITY,
	COMMENT_TEXT VARCHAR(500)
);

CREATE TABLE bft.BELIEF_REFERENCES(
	BELIEF_REFERENCES_ID INTEGER NOT NULL IDENTITY,
	BELIEF_ID INTEGER NOT NULL,
	REFERENCE_ID INTEGER NOT NULL
);

CREATE TABLE bft.ADHERENCE(
	ADHERENCE_ID INTEGER NOT NULL IDENTITY,
	TYPE_CODE VARCHAR(10) NOT NULL,
	COMMENT_TEXT VARCHAR(500)
);

CREATE TABLE bft.BELIEF_ADHERENCES(
	BELIEF_ADHERENCES_ID INTEGER NOT NULL IDENTITY,
	BELIEF_ID INTEGER NOT NULL,
	ADHERENCE_ID INTEGER NOT NULL
);

CREATE TABLE bft.PERSON(
	PERSON_ID INTEGER NOT NULL IDENTITY,
	PERSON_NAME VARCHAR(100)
);

CREATE TABLE bft.PERSON_REFERENCES(
	PERSON_REFERENCES_ID INTEGER NOT NULL IDENTITY,
	PERSON_ID INTEGER NOT NULL,
	REFERENCE_ID INTEGER NOT NULL
);

CREATE TABLE bft.HERITAGE(
	HERITAGE_ID INTEGER NOT NULL IDENTITY,
	TYPE_CODE VARCHAR(10) NOT NULL,
	HERITAGE_SEQ INTEGER NOT NULL,
	PARENT_PERSON_ID INTEGER,
	PARENT_BELIEF_ID INTEGER,
	COMMENT_TEXT VARCHAR(500)
);

CREATE TABLE bft.BELIEF_HERITAGES(
	BELIEF_HERITAGES_ID INTEGER NOT NULL IDENTITY,
	BELIEF_ID INTEGER NOT NULL,
	HERITAGE_ID INTEGER NOT NULL
);

CREATE TABLE bft.CONCEPT(
	CONCEPT_ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(100) NOT NULL,
	COMMENT_TEXT VARCHAR(500)
);

CREATE TABLE bft.BELIEF_CONCEPTS(
	BELIEF_CONCEPT_ID INTEGER NOT NULL IDENTITY,
	BELIEF_ID INTEGER NOT NULL,
	CONCEPT_ID INTEGER NOT NULL
);

CREATE TABLE bft.DIVINITY(
	DIVINITY_ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(100) NOT NULL,
	COMMENT_TEXT VARCHAR(500)
);

CREATE TABLE bft.BELIEF_DIVINITIES(
	BELIEF_DIVINITY_ID INTEGER NOT NULL IDENTITY,
	BELIEF_ID INTEGER NOT NULL,
	DIVINITY_ID INTEGER NOT NULL
);


